## kubectl get configmap aws-auth -n kube-system -o yaml
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::913733009480:role/eksctl-roboshop-gmd-new-nodegroup--NodeInstanceRole-AEJLFWbiaCnW
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::913733009480:user/gopi
      username: gopi
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::913733009480:user/chand
      username: chand
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: e7d687f2-71af-4b3f-84c2-e42e71fc208e
